version: '3.8'
services:
  db:
    image: postgres:16-alpine

    environment:
      POSTGRES_USER: ${POSTGRES_USER:?Required variable POSTGRES_USER not set}
      POSTGRES_DB: ${POSTGRES_DB:?Required variable POSTGRES_DB not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Required variable POSTGRES_PASSWORD not set}

    ports:
      - 127.0.0.1:5432:5432
